version: '3.8'

networks:
  gv_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
services:
  postgres:
    container_name: gestao_vagas_postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gestao_vagas
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - gv_network
    ports:
      - 9090:9090
  grafana: 
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - gv_network
    ports:
      - 3000:3000
   
  sonarqube:
    image: sonarqube:9.9-community
    container_name: gestao_vagas_sonarqube
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
        - 9000:9000
    restart: always